// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using EnvironmentApplication.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Categories> Categories { get; set; }
    public virtual DbSet<Taxpayer> Taxpayer { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new CategoriesConfiguration());
        modelBuilder.ApplyConfiguration(new TaxpayerConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}